### ISSUE TITLE
Really bad name

### ISSUE THREAD

**Issue by maandree** [LaPingvino/e#2]
I would strongly advise that you choose a longer name, as people use single and double letter commands as aliases. Personally, I have e aliased to my preferred text editor ($EDITOR), this would case problems for me if I choosed to also use your editor. I would suggest using at least 3 letters. Another issue is name conflict with other project.

**Comment by LaPingvino** [comment]
I didn't find clashes with other projects yet, and you can install it with whatever name you want on your system. The extremely short name is one of the design goals. You can alias this to a longer name too if you want :).

**Comment by maandree** [comment]
Consider what would happen if someone else makes a text editor named e. Do you think he will find yours? I imagine he would pretty much only be able to find it if he uses one if the distributions your editor is distributed on. In some distributions his editor will be distributed as e, and under other distributions it will be distributed under some other name. And the command name will be different on different distributions. And I'm not so sure yours is the first project named e, not even the first text editor: https://github.com/etexteditor/e.

**Comment by LaPingvino** [comment]
I don't expect any distribution to carry this editor any time soon, and in the AUR the name was free so I added it there. The one you point to has a squatted domain name, looks to be a graphical editor and severely out of date. This is a line editor, like ed and ex, and the name is picked in that line/tradition, and to be easy to use from the command line, where I will be typing this a lot already. Of course when it turns out that a conflict arises, like a similar issue with Go (which has a short and hard to google name for similar reasons), it's easy to remedy that. In any case where a clash may occur, I suggest here `e-line-editor` as the official alternative name.
